language: python
dist: xenial
sudo: false

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install tox coveralls
matrix:
  include:
    - python: 2.7
      env:
          - ENV=docs
    - python: 3.5
      env:
          - ENV=py35-django21
    - python: 3.6
      env:
          - ENV=py36-django21
script:
  - tox
after_success:
  - coveralls
