language: python

install:
  - pip install tox coveralls
matrix:
  include:
    - python: 3.5
      env:
          - ENV=py35-django21
    - python: 3.6
      env:
          - ENV=py36-django21
script:
  - tox -e $ENV
after_success:
  - coveralls
